"""
Split the Input Data into Left and Right Halves: 
You start with a 64-bit block of data. Split this block into two 32-bit halves, 
left_half and right_half (use masking and shifting)

Expand the Right Half using the E-box: 
The right half (32 bits) needs to be expanded to 48 bits using the E-box. 

Use the general permute function with the E-box table: 
expanded_right = permute(right_half, e_box_table, 32)

Mix the Expanded Right Half with the Round Key: 
XOR the 48-bit expanded right half with the 48-bit round key generated by your key scheduling algorithm.

Substitute Using S-boxes: This is code you've already written. Something like:
substituted_data = s_boxes(mixed_data)
"""
e_box_table = [
        32, 1, 2, 3, 4, 5,
        4, 5, 6, 7, 8, 9,
        8, 9, 10, 11, 12, 13,
        12, 13, 14, 15, 16, 17,
        16, 17, 18, 19, 20, 21,
        20, 21, 22, 23, 24, 25,
        24, 25, 26, 27, 28, 29,
        28, 29, 30, 31, 32, 1
    ]

def permute(data: int, table: list, bit_length: int) -> int:
    """
    General permutation function that applies the given permutation table to the data.
    
    Args:
        data: The input data to permute (int).
        table: The permutation table (list of bit positions).
        bit_length: The number of bits in the output (e.g., 48 for PC-2, 32 for P-box).
    
    Returns:
        The permuted data (int).
    """
    permuted_data = 0
    for i, pos in enumerate(table):
        permuted_data |= ((data >> (bit_length - pos)) & 1) << (len(table) - 1 - i)
    return permuted_data

pc1_table = [
        57, 49, 41, 33, 25, 17, 9,
        1, 58, 50, 42, 34, 26, 18,
        10, 2, 59, 51, 43, 35, 27,
        19, 11, 3, 60, 52, 44, 36,
        63, 55, 47, 39, 31, 23, 15,
        7, 62, 54, 46, 38, 30, 22,
        14, 6, 61, 53, 45, 37, 29,
        21, 13, 5, 28, 20, 12, 4
    ]

pc2_table = [
        14, 17, 11, 24, 1, 5,
        3, 28, 15, 6, 21, 10,
        23, 19, 12, 4, 26, 8,
        16, 7, 27, 20, 13, 2,
        41, 52, 31, 37, 47, 55,
        30, 40, 51, 45, 33, 48,
        44, 49, 39, 56, 34, 53,
        46, 42, 50, 36, 29, 32
    ]

def key_schedule(des_key_64_bits: int) -> list[int]:
    """
    Takes a 64-bit DES key as input and returns a list of 16 round keys, each 48 bits long.
    """
    # Permuted Choice 1 (PC-1)
    permuted_key = permute(des_key_64_bits, pc1_table, 64)
    
    # Split the key into two 28-bit halves
    left_half = permuted_key >> 28          # 28-bit left half
    right_half = permuted_key & 0x0000000fffffff     # 28-bit right half
    
    round_keys = []     # will be returned in the end
    shift_schedule = [1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1]
    
    for round_num in range(16):
        # Apply left shifts according to the shift schedule
        left_half = (left_half << shift_schedule[round_num] & 0xfffffff) | (left_half >> (28 - shift_schedule[round_num]))
        right_half = (right_half << shift_schedule[round_num] & 0xfffffff) | (right_half >> (28 - shift_schedule[round_num]))
        
        # Combine the halves and apply Permuted Choice 2 (PC-2)
        combined_key = (left_half << 28) | (right_half) 
        round_key = permute(combined_key, pc2_table, 56)
        round_keys.append(hex(round_key))
    
    return round_keys

#Mix the Expanded Right Half with the Round Key: 
#XOR the 48-bit expanded right half with the 48-bit round key generated by your key scheduling algorithm.

def expand_key(input_data):
    left_half = input_data >> 32          # 32-bit left half
    right_half = input_data & 0x00000000ffffffff    # 32-bit right half

    expanded_right = permute(right_half, e_box_table, 32)

    round_keys = key_schedule(input_data)

    xored_right = bytes(byte_a ^ byte_b for byte_a, byte_b in zip(expanded_right, round_keys))



    

